### ISSUE TITLE
Tachio should store any comments and attachments from all incoming webhooks to Supabase for future retrieval based on their Missive conversation ID

### ISSUE THREAD

**Issue by ejfox** [room302studio/coachartie#55]

**Comment by rajivsinclair** [comment]
I don’t see any new tables in our Supabase and I don’t see any new records in our existing tables “memories” and “messages”. Do you need me to make any adjustments for you in Supabase? You should already have the permission to access our Supabase and make changes to the data structure so that Tachio can store memories and messages in our Supabase (and only in our Supabase).
